# Generated by Django 2.2.2 on 2019-06-21 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_date', models.DateTimeField()),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
                ('departure_timestamp', models.CharField(blank=True, max_length=255, null=True)),
                ('arrival_timestamp', models.CharField(blank=True, max_length=255, null=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('price_adult', models.FloatField(blank=True, null=True)),
                ('price_child', models.FloatField(blank=True, null=True)),
                ('price_infant', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onward', models.BooleanField(default=True)),
                ('carrier', models.CharField(blank=True, max_length=255, null=True)),
                ('flight_number', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
                ('departure_timestamp', models.CharField(blank=True, max_length=255, null=True)),
                ('arrival_timestamp', models.CharField(blank=True, max_length=255, null=True)),
                ('flight_class', models.CharField(blank=True, max_length=10, null=True)),
                ('number_of_stops', models.IntegerField(blank=True, null=True)),
                ('ticket_type', models.CharField(blank=True, max_length=10, null=True)),
                ('warning_text', models.TextField(blank=True, null=True)),
                ('itinerary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flight.Itinerary')),
            ],
        ),
    ]
